Adding Dashboard with placeholder widgets
maxxxxxdlp/calendar-stats pull request #34
Opened 2022-09-19 00:53 UTC by Durbatuluk1701

Not yet ready to merge, just opening for viewing

2022-09-19 00:54 UTC, maxxxxxdlp commented
Awesome. In that case, I converted it to a `Draft Pull Request`. You can convert it back once it is ready

2022-09-19 00:56 UTC, Durbatuluk1701 commented
Couple things to note:
- I think we should add a scrollbar to the dashboard, probably a separate story (either that or we should workshop how we want the dashboard to look a bit more)
- I do not quite understand the Tailwind style for styling element, probably could be refactored to work into Tailwind soon. 
- Seems to be an issue with the "Create" button for google calendar rendering over the Dashboard, need to look more into how the Portal works and why it cannot show up above it

2022-09-19 02:27 UTC, maxxxxxdlp commented
Do you want to look into [Tailwind documentation](https://tailwindcss.com/docs/editor-setup) and refactor the code to use tailwind class names, or do you want me to refactor it?

2022-09-19 13:26 UTC, Durbatuluk1701 commented
I will refactor for Tailwind as long as this PR isn't massively blocking others, just will take some time to read the docs and refactor.

2022-09-19 20:13 UTC, Durbatuluk1701 commented
Ready for review and discussion. Feel like there may be some more work to tweak the widgets to look more how we want, but until I have a better idea of how we want to format it I am not really sure

2022-09-19 23:36 UTC, maxxxxxdlp requested changes

2022-09-19 23:36 UTC, maxxxxxdlp commented on src/src/declarations.d.ts
> +
This file is only for changing the type definitions of default javascript methods to make them more type safe.

Your custom typings should probably go into a different file. `./index.tsx` or `./Dashhboard/index.tsx` would be a good place for this at the moment.

Though, if you **really** want the type to be in global scope, then create a separate `.d.ts` file and put `WidgetObj` there

2022-09-19 23:36 UTC, maxxxxxdlp commented on src/src/components/App/index.tsx
> +// Allowing for the class to me overriden from here
a typo: `to me overriden`
should be `to be overriden`

2022-09-19 23:36 UTC, maxxxxxdlp commented on src/src/components/Dashboard/index.tsx
> +                <h1 className='mx-auto my-0 text-center'>DASHBOARD</h1>
[non-blocking]

The `DASHBOARD` text is probably just temporary at this point, but for the, could you please add any text strings into the `common.tsx` file in this directory - https://github.com/maxxxxxdlp/calendar-stats/tree/main/src/src/localization

Then, you can call it in code like `commonText('yourKey')`

You can also provide optional attributes to that function (like `commonText('key', 1, 2, 3)`).

See the [`README.md`](https://github.com/maxxxxxdlp/calendar-stats/tree/main/src/src/localization#readme) for more documentation

2022-09-19 23:36 UTC, maxxxxxdlp commented on src/src/components/Molecules/Portal.tsx
> +    element.className = "h-full"
[non-blocking]

Could you enable the `prettier` plugin in your IDE to keep the code formatting consistent?

2022-09-20 14:19 UTC, maxxxxxdlp approved these changes

2022-09-20 14:27 UTC, merged